### ISSUE TITLE
Add 'Add' capability for users

### ISSUE THREAD

**Issue by spoetnik** [scottwoodall/django-react-template#1]
Could you please add 'Add' functionality for users?
Your repo is a great learning for me and I would love to see how to handle the Create functionality.

Thanks for sharing this!

**Comment by scottwoodall** [comment]
Create functionality has been added in [this commit](https://github.com/scottwoodall/django-react-template/commit/078cb1327806d6ab9b2b070d19604680107f938b).

Let me know if you run into any issues with it. Cheers!

**Comment by spoetnik** [comment]
Thanks!
