### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by xTEddie** [scottwoodall/django-react-template#13]
Hello, I am trying to build an application using ReactJS and Django. I used Django templates for users to log in the application and it is using the default auth.users model given from Django. Once the user is logged in, ReactJS is used to render the views by making calls to the django REST framework. I would like to make the API calls private, so users must be authenticated in order to use it. Also, the database does not store any passwords because the users are authenticated with LDAP. So, the ReactJS is used to make REST calls and render data. Right now the permission is set to AllowAll because I was not able to use the permission IsAuthenticated. 

Django by default stores data in the session and cookies once the user is logged. I was trying to get those session and cookies data everytime someone make a GET or POST request to verify the authentication. I tried to use reactJS to make a rest call and django always says that the request.user is Anonymous. 

I have been trying to solve this issue and did not find a solution. Do you have any suggestion to solve this issue?

I tried to use "rest_framework.permissions.IsAuthenticated" and I always get a 403.

**Comment by scottwoodall** [comment]
Does the authenticated user have access to the model you are trying to access? Does this problem have a fresh clone/start of this project or have you modified this project in some way when you receive the error.

**Comment by xTEddie** [comment]
The user is authenticated using LDAP. If the user's credentials is valid, the user's info (firstname, lastname, username) are stored in the default django auth.model, but not the password. I am able to set the user to superuser and staff with that module's command. I used this module to set this up : https://github.com/etianen/django-python3-ldap

My project is done from scratch, but it is highly based on yours. I thank you for that! I also tested your project and it seems that everything is working fine but I couldn't find a way to make it work on my part.

**Comment by xTEddie** [comment]
Do I have to set a specific permission in order to access for the REST framework API even if the user is a superuser and staff?

**Comment by scottwoodall** [comment]
If the user is a superuser then I don't think Django's model permissions are the problem. I'd have to see the source code of your project to help debug further.

**Comment by xTEddie** [comment]
Unfortunately, the project is for a client, so it is not possible to share the code. I tried to debug further. I get the status code 401 actually. Is there any specific request headers that I have to send? 

Whenever I navigate into any pages that is written using django templates, I see the user is authenticated. But when I navigate into a page that is written using ReactJS components, I see that the user is not authenticated, but clearly the user is authenticated since I am able to navigate to that page.

**Comment by scottwoodall** [comment]
Make sure your AJAX request is sending the Django cookie. Are you able to copy/paste the REST request into your browser and see what happens?

**Comment by xTEddie** [comment]
It did not work in the end. I went on another route, I send the session_key from the request object to the window object in the django template. ReactJS would catch the session_key and send that add it in the headers for GET/POST requests. I created my own permission class to check for the headers. I really appreciate for the help though. Thank you very much!

**Comment by scottwoodall** [comment]
Sounds good! Something else to check if you feel up to it. Check the `secure` flag on the Django cookie. If this flag is set and your devserver is running over port 80 then your browser will never send the cookie. There's probably something misconfigured with the cookies if you're having to set a `window.session_key` to get access to it.

**Comment by xTEddie** [comment]
Hello, just for an update. I found a solution for this issue. I had to add **credentials: 'same-origin'** in the payload: 

        let requestHeaders = new Headers({
            "X-CSRFToken": window.django.csrf,
        });

        let payload = {
            method: 'POST',
            headers: requestHeaders,
            credentials: 'same-origin'
        };

        fetch(API_URL, payload)
