### ISSUE TITLE
Documentation request :: Add own app

### ISSUE THREAD

**Issue by spoetnik** [scottwoodall/django-react-template#4]
Could you please document how to add a new app (besides emailusers) to the template?

**Comment by scottwoodall** [comment]
1. For the frontend; copy the directory and all files into a new directory, i.e. `cp -R frontend/src/app/users frontend/src/app/foobar`. Then open and edit each file accordingly.
1. Open `frontend/src/app/rootReducer.js` and add in your new `frontend/src/app/foobar/reducers.js`
1. Open `frontend/src/app/urls.js` and add in your new `frontend/src/app/foobar/urls.js`
1. Edit `backend/templates/backend/app.html` and add in the url for the new app created on the Django side (i.e. `foobar: "{% url "foobar-list" %}"`

**Comment by spoetnik** [comment]
Thanks for writing this out.

Is the frontend structure based on a know react.redux boilerplate?
Love the per-app structure!

**Comment by scottwoodall** [comment]
No problem. I updated the note with what file to edit if you need to add an icon to the sidebar.

Cheers!

**Comment by scottwoodall** [comment]
I don't know that my code is based on any specific layout. Just a layout that makes sense to me and some tips/tricks I've picked up over time.

**Comment by dmk23** [comment]
I am looking at converting a Django application with a few dozen models into React UI

The method outlined here suggests a massive amount of duplication if we are going to create an "app" per model, essentially copying the same code over and over

Are there any patterns / best practices to automate / parametrize this process? Seems to me generating lots of small files with lots of duplication is a recipe for maintenance disaster.

Any suggestions / examples would be greatly appreciated!

**Comment by scottwoodall** [comment]
This project is meant to be a boilerplate to get the basic scaffolding up and running. If you're dealing with straight CRUD then I imagine some of these files could be refactored to account for that but it's a decisions I've chose to leave up to the developer.

**Comment by dmk23** [comment]
We do have a lot more than CRUD and I think I'll have more questions as functionality gets fleshed out

For now we'll be preserving your existing directory structure and just put multiple entities in the same files (e.g. 20 create forms in one files) for ease of management by compare / copy / paste. We are also adding new files for additional components, not present in basic CRUD

Will report on the progress - this project is our utmost priority :)
