### ISSUE TITLE
Default project problems

### ISSUE THREAD

**Issue by ArcaneWater** [scottwoodall/django-react-template#5]
So i have just cloned and started fresh project, and my default project is not realy working. At entry site it shows login form without any css, and at admin i get following error:

subclasses of AbstractBaseUser must provide a get_short_name() method.

What am i doing wrong here?

**Comment by scottwoodall** [comment]
Hey there. Cloning the repo won't get you very far. This is a project meant to interact with the django-admin.py command.

Have you had a chance to read over the installation section in the README?

https://github.com/scottwoodall/django-react-template/blob/master/README.md

**Comment by ArcaneWater** [comment]
Yes i did it exactly as it says in readme with django-admin.py startproject, but no success

**Comment by scottwoodall** [comment]
I went through the three different README's to start a new project and I wasn't able to reproduce the errors. Are you also following the steps in the [frontend README](https://github.com/scottwoodall/django-react-template/blob/master/frontend/README.md) and [backend README](https://github.com/scottwoodall/django-react-template/blob/master/backend/README.md)?

If you've followed the steps in all three README's would you mind starting a brand new project and go through these steps and then if you continue to get the same error can you share a screenshot of your termnial where you have ran all the commands?

**Comment by ArcaneWater** [comment]
Got it working now failed to run npm start, sorry and thanks!
