### ISSUE TITLE
Logout & logged in user profile

### ISSUE THREAD

**Issue by dmk23** [scottwoodall/django-react-template#6]
First, thanks for this excellent starter project - I was able to get it up and running.

However I cannot seem to find a way to log out from the app in the current template. Sign Out link fails. It would also be helpful to provide some very basic self-management functionality to user profiles.

Any pointers / suggestions are appreciated, just getting started with React on Django...

**Comment by scottwoodall** [comment]
The "Sign Out" link previously had it's anchor tag set to `#`. I've added the default Django logout view to handle this and wired it up on the [frontend in this commit.](https://github.com/scottwoodall/django-react-template/commit/ede09041a4575cb7e3d3c5a75dde9e3080785c07)

I'm going to leave the profiles stuff for another day. Here's some [tips on getting started in another issue.](https://github.com/scottwoodall/django-react-template/issues/4)

**Comment by dmk23** [comment]
Thank you - the fix confirmed to work!
