### ISSUE TITLE
frontend build scripting

### ISSUE THREAD

**Issue by dmk23** [scottwoodall/django-react-template#7]
I am looking to add the React frontend to our automated build/deploy environment

Right now the frontend instructions rely on `npm start` which builds the project but then keeps running / does not exit which makes this command unsuitable for use in automated build scripts.

How to build the frontend with a command that would exit? Would that require any changes to project setup? Being new to npm development not sure what is the right answer ...

**Comment by scottwoodall** [comment]
Take a look at `frontend/package.json`. Within it you can define different custom commands under `scripts`.

One of scripts listed for this project is `build:webpack`. You can use this for automated builds by running:

`npm run build`

which will use the `webpack.config.prod.js` file and your files will show up in `frontend/dist`

**Comment by scottwoodall** [comment]
Let me know if my above doesn't answer your question and I'll continue to help out.

**Comment by dmk23** [comment]
Thank you, Scott. Your help is greatly appreciated!

Now I do see the point of using `npm start` and have observed reloading - even though it does not seem to always work when files are changed

Could it be possible to use run a build command with a development webpack config? I'm still considering various options for our build process setup and this one might be handy as well...

**Comment by scottwoodall** [comment]
Is VIM your editor? If so [check out this thread](https://github.com/webpack/webpack/issues/781) regarding files changing and triggering the webpack build process.

This project uses two different webpack config files: `frontend/webpack.config.dev.js` and `frontend/webpack.config.prod.js`.

You're free to create additional webpack configs and/or create additional `npm scripts` within `frontend/package.json` to meet your needs.

**Comment by dmk23** [comment]
Not using VIM, in fact considering various new options for JS editing, for now with Notepad Plus.

Auto-reloading is not the biggest issue anyways, seems like having to trigger build script by hand before re-testing something is not a significant problem...
